from collections import defaultdict
from pathlib import Path

import logging

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4

from sqlalchemy.orm import Session

from app.db.models.invoice import InvoiceModel

logger = logging.getLogger(__name__)

REPORTS_DIR = Path("app/reports")

styles = getSampleStyleSheet()


def generate_invoice_report(
    session: Session,
    invoice_id: int
) -> str:

    invoice = (
        session.query(InvoiceModel)
        .filter(InvoiceModel.id == invoice_id)
        .first()
    )

    if not invoice:
        raise ValueError("Invoice not found")

    REPORTS_DIR.mkdir(exist_ok=True)

    pdf_path = REPORTS_DIR / f"invoice_{invoice_id}.pdf"

    #If PDF already exists, return it instead of creating a new one
    if pdf_path.exists():
        return str(pdf_path)

    doc = SimpleDocTemplate(
        str(pdf_path),
        pagesize=A4
    )

    elements = []

    # sections
    elements.extend(build_header())
    elements.extend(build_metadata(invoice))
    elements.extend(build_line_items_table(invoice))
    elements.extend(build_category_summary(invoice))
    elements.extend(build_totals(invoice))
    elements.extend(build_footer())

    doc.build(elements)

    return str(pdf_path)

def build_header():

    return [
        Paragraph(
            "<b>EXPENSE REPORT</b>",
            styles["Title"]
        ),
        Spacer(1, 20)
    ]

def build_metadata(invoice):

    metadata = f"""
    <b>Vendor:</b> {invoice.issuer_name}<br/>
    <b>Date:</b> {invoice.invoice_date}<br/>
    <b>Invoice #:</b> {invoice.invoice_number}<br/>
    <b>Currency:</b> {invoice.currency}<br/>
    <b>Extraction Method:</b> {invoice.extraction_method}
    """

    return [
        Paragraph(metadata, styles["BodyText"]),
        Spacer(1, 20)
    ]

def build_line_items_table(invoice):

    data = [
        ["#", "Item", "Category", "Qty", "Amount"]
    ]

    for idx, item in enumerate(invoice.line_items, start=1):

        description = item.description[:35]

        data.append([
            str(idx),
            description,
            item.category,
            str(item.quantity),
            f"{item.amount:.2f}"
        ])

    table = Table(
        data,
        colWidths=[30, 220, 100, 50, 70]
    )

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),

        ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),

        ("GRID", (0, 0), (-1, -1), 1, colors.black),

        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),

        ("ALIGN", (3, 1), (4, -1), "RIGHT"),
    ]))

    return [
        table,
        Spacer(1, 20)
    ]

def build_category_summary(invoice):

    category_totals = defaultdict(float)

    for item in invoice.line_items:
        category_totals[item.category] += item.amount

    data = [["Category", "Total"]]

    for category, total in category_totals.items():
        data.append([
            category,
            f"{total:.2f}"
        ])

    table = Table(
        data,
        colWidths=[250, 100]
    )

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),

        ("GRID", (0, 0), (-1, -1), 1, colors.black),

        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]))

    return [
        Paragraph(
            "<b>CATEGORY SUMMARY</b>",
            styles["Heading2"]
        ),
        Spacer(1, 10),
        table,
        Spacer(1, 20)
    ]

def build_totals(invoice):

    total_text = f"""
    <b>TOTAL:</b> {invoice.total_amount:.2f} {invoice.currency}
    """

    return [
        Paragraph(
            total_text,
            styles["Heading2"]
        ),
        Spacer(1, 20)
    ]

def build_warnings(invoice):

    warnings = getattr(invoice, "warnings", None)

    if not warnings:
        return []

    content = "<br/>".join(
        [f"• {warning}" for warning in warnings]
    )

    return [
        Paragraph(
            "<b>Warnings</b>",
            styles["Heading2"]
        ),
        Spacer(1, 10),

        Paragraph(
            content,
            styles["BodyText"]
        ),

        Spacer(1, 20)
    ]

def build_footer():

    return [
        Paragraph(
            "Generated by AI Invoice Processor",
            styles["Italic"]
        )
    ]